#!/usr/bin/env bash
# Generated-file guard — routes edits of script-generated files back to the generator
#
# Triggered by: PreToolUse on Edit|Write
# Purpose: a doc-only fix to a generated file survives exactly one rerun of its
#          generator. Registry: .claude/generated-outputs.tsv
#
# Exit codes:
#   0 = allow (not in the registry, or registry mode is `warn`)
#   2 = BLOCK (pure generator output — edit the generator instead)
#
# FAIL-OPEN ON INFRASTRUCTURE, FAIL-CLOSED ON DATA. If python3 is missing or the
# registry is unreadable, this hook allows the edit: a bug here must never brick every
# Edit/Write in the session. But a registry ROW that is present and malformed blocks,
# rather than silently degrading to `warn` — a guard that reassures you while letting
# the edit through is worse than no guard.
#
# Registry format (TSV): glob<TAB>generator-command<TAB>mode   mode is block or warn.
# Dormant (exit 0) when the registry file is absent.

set -uo pipefail
trap 'exit 0' ERR

ROOT="${CLAUDE_PROJECT_DIR:-$(pwd)}"
ROOT="${ROOT%/}"                      # a trailing slash here used to disarm the whole hook
REGISTRY="$ROOT/.claude/generated-outputs.tsv"

[ -f "$REGISTRY" ] || exit 0

INPUT=$(cat)

# Normalize the path here, not with shell prefix-stripping: `./x`, `a/../x`, `//x` and
# symlinks all evaded a plain "${FILE#$ROOT/}" strip.
REL=$(ROOT="$ROOT" python3 -c "
import sys, json, os
try:
    d = json.loads(sys.stdin.read())
    ti = d.get('tool_input', d)
    p = ti.get('file_path', '')
    if not p:
        print(''); raise SystemExit
    root = os.path.realpath(os.environ['ROOT'])
    p = os.path.realpath(os.path.join(root, p))
    print(os.path.relpath(p, root))
except Exception:
    print('')
" <<< "$INPUT" 2>/dev/null)

[ -n "$REL" ] || exit 0
case "$REL" in ..*|/*) exit 0 ;; esac   # outside the repo — not ours

lineno=0
while IFS=$'\t' read -r glob generator mode || [ -n "${glob:-}" ]; do
  lineno=$((lineno + 1))
  case "$glob" in ''|'#'*) continue ;; esac

  # shellcheck disable=SC2053  # intentional glob match, not string equality
  [[ $REL == $glob ]] || continue

  mode="${mode//$'\r'/}"                       # CRLF from a macOS/Windows editor
  mode="$(printf '%s' "${mode:-}" | tr -d '[:space:]' | tr '[:upper:]' '[:lower:]')"

  if [ "$mode" = "warn" ]; then
    echo "WARNING: $REL is generated by $generator." >&2
    echo "This file also carries hand-signed content, so the edit is allowed." >&2
    echo "If you are changing boilerplate or a header, change the generator instead." >&2
    exit 0
  fi

  if [ "$mode" != "block" ]; then
    echo "BLOCKED: $REL matched a MALFORMED registry row (line $lineno of" >&2
    echo ".claude/generated-outputs.tsv): mode is '${mode:-<empty>}', expected block or warn." >&2
    echo "Blocking rather than guessing. Fix the row, then retry." >&2
    exit 2
  fi

  echo "BLOCKED: $REL is generated by $generator." >&2
  echo "Edit the generator and re-run it. A doc-only fix has a one-run half-life." >&2
  echo "If this file is genuinely hand-maintained, remove its row from .claude/generated-outputs.tsv." >&2
  exit 2
done < "$REGISTRY"

exit 0
